// --------------------------------------------------------------------------------------------------------------------
// <copyright company="Aspose" file="postBarcodeRecognizeFromUrlOrContentRequest.java">
//   Copyright (c) 2021 Aspose.BarCode for Cloud
// </copyright>
// <summary>
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

//
// This source code was auto-generated by AsposeBarcodeCloudCodegen.
//

package com.aspose.barcode.cloud.requests;

import com.aspose.barcode.cloud.model.*;

import java.io.File;
import java.util.List;

public class postBarcodeRecognizeFromUrlOrContentRequest {
    public String type;
    public String checksumValidation;
    public Boolean detectEncoding;
    public String preset;
    public Integer rectX;
    public Integer rectY;
    public Integer rectWidth;
    public Integer rectHeight;
    public Boolean stripFNC;
    public Integer timeout;
    public Integer medianSmoothingWindowSize;
    public Boolean allowMedianSmoothing;
    public Boolean allowComplexBackground;
    public Boolean allowDatamatrixIndustrialBarcodes;
    public Boolean allowDecreasedImage;
    public Boolean allowDetectScanGap;
    public Boolean allowIncorrectBarcodes;
    public Boolean allowInvertImage;
    public Boolean allowMicroWhiteSpotsRemoving;
    public Boolean allowOneDFastBarcodesDetector;
    public Boolean allowOneDWipedBarsRestoration;
    public Boolean allowQRMicroQrRestoration;
    public Boolean allowRegularImage;
    public Boolean allowSaltAndPepperFiltering;
    public Boolean allowWhiteSpotsRemoving;
    public Boolean checkMore1DVariants;
    public Double regionLikelihoodThresholdPercent;
    public List<Integer> scanWindowSizes;
    public Double similarity;
    public Boolean skipDiagonalSearch;
    public Boolean readTinyBarcodes;
    public String australianPostEncodingTable;
    public String rectangleRegion;
    public String url;
    public File image;

    public postBarcodeRecognizeFromUrlOrContentRequest() {}
}
