name: Java check style

on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 11

    - name: Lint with CheckStyle
      run: ./scripts/checkstyle.bash
