# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        # Use same in Dockerfile
        distribution: 'corretto'
        java-version: 11
        # cache: 'maven'

    - name: Maven Compile
      run: mvn compile

    - name: Test with Maven
      env:
        TEST_CONFIGURATION_ACCESS_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}
      run: |
        chmod +x scripts/*
        ls .
        ls ./target
        ls ./target/lib
        make test

    # TODO: Move to pack.yml
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile
